\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename anju.info
@settitle Anju User Guide
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@paragraphindent none
@c %**end of header

@copying
Copyright © 2026 Charles Y@. Choi
@end copying

@dircategory Emacs misc features
@direntry
* Anju: (anju).         A package for customizing Emacs mouse interactions.
@end direntry

@finalout
@titlepage
@title Anju User Guide
@subtitle for version 1.5.3-rc.1
@author Charles Y@. Choi (@email{kickingvegas@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Anju User Guide

Version: 1.5.3-rc.1

Copyright © 2026 @w{Charles Y. Choi}

Anju (안주) is a project to align mouse interactions in Emacs with contemporary (circa 2026) expectations. Effort towards this alignment is made in the following areas:

@itemize
@item
Context-sensitive menus
@item
De-emphasis of middle mouse button usage (binding @samp{<mouse-2>})
@item
Support direct manipulation when possible
@item
Re-organization of the menu bar
@end itemize

The features offered by Anju are opinionated@comma{} but avoids unconventional behavior. Anju aspires to bring a calmer mouse experience to Emacs.

Please note that all UI terminology in this document is Emacs-centric and differs from conventional GUI terminology. Refer to (emacs) Frames (@ref{Frames,emacs#Frames,,emacs,}) for more detail on this.

It costs money to make@comma{} enhance@comma{} and maintain Anju as ideologically free software. If you enjoy using Anju@comma{} please buy me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@end ifnottex

@menu
* Motivation::
* Features::
* Requirements::
* Install::
* Customization::
* Future Work::
* Feedback & Discussion::
* Sponsorship::
* About Anju::
* Acknowledgments::
* Main Index::
* Variable Index::

@detailmenu
--- The Detailed Node Listing ---

Motivation

* Design Principles and Concerns::

Features

* Mode Line Features::
* Context Menu Features::
* Main Menu Features::
* Window Management Features::

Context Menu Features

* Selected Text Commands::
* Org Mode Context Menu::
* Dired Mode Context Menu::
* Info Context Menu::
* Emacs Lisp Context Menu::
* Compilation/Grep Context Menu::
* Makefile Context Menu::
* Rectangle Context Menu::
* Version-Controlled Source::

Org Mode Context Menu

* Org Headline Context Menu::
* Org Item Context Menu::
* Org Table Context Menu::
* Org Insert Link::
* Org Toggle Images & Show Markup::
* Org “Copy as…” Context Menu::
* Org Paste Context Menu::

Emacs Lisp Context Menu

* Basic Elisp Context Menu::
* Edebug Mode Context Menu::
* ERT Support::
* Extract Lambda (𝜆) Expression::

Main Menu Features

* File Menu Features::
* Edit Menu Features::
* Options Menu Features::
* Bookmarks Menu Features::
* Text Menu Features::
* Index Menu (imenu) Features::
* Tools Menu Features::
* Help Menu Features::

Tools Menu Features

* Macro Recorder Menu::

Customization

* Anju Initialization (@code{anju-init})::
* Context Menu Customization::
* Mode Line Buffer List Menu Customization::
* Main Menu Customization::

Context Menu Customization

* Customizing context-menu-functions::
* Anju Context Menu Functions::

Main Menu Customization

* File Menu Customization::
* Edit Menu Customization::
* Options Menu Customization::
* Text Menu Customization::
* Bookmarks Menu Customization::
* Help Menu Customization::
* Imenu Menu Customization::
* Tools Menu Customization::

@end detailmenu
@end menu

@node Motivation
@chapter Motivation

@cindex Motivation

The Anju package is intended to change the default mouse interactions in Emacs for the following reasons:

@itemize
@item
Uneven implementation of context-sensitive menus for different modes.
@item
Over-commitment to legacy usage of the middle mouse button.
@item
Lengthy menus that feel more like an inventory of commands rather than a designed user experience.
@item
Over-reliance on mouse workflows that require switching between the mouse and keyboard.
@end itemize

Anju makes opinionated design decisions@comma{} but avoids unconventional behavior. Anju aspires to bring a calmer mouse experience to Emacs.

Elaboration on what informs Anju's opinions is described below.

@menu
* Design Principles and Concerns::
@end menu

@node Design Principles and Concerns
@section Design Principles and Concerns

@cindex Design Principles and Concerns

This section conveys the principles and concerns used by Anju to inform its design decisions.

Editorially@comma{} all design decisions for Anju are ultimately the opinion of Charles Y@. Choi.


@subheading General Principles

@itemize
@item
Menus should be organized.
@itemize
@item
A coherent information architecture should be conveyed.
@item
Balance between concision and discoverability should be made in a menu's offerings.
@end itemize
@item
Nesting of sub-menus should be carefully considered@comma{} ideally not exceeding a depth of two.
@item
Mouse workflows that require keyboard input should be minimized.
@item
If the opportunity to provide a direct manipulation experience is available@comma{} it should be taken.
@item
Unconventional mouse interactions should be avoided.
@end itemize

@subheading Concerns

Anju takes the position that different types of menus have different concerns or objectives. This is most apparent in contrasting the design of a main menu section (e.g. File@comma{} Edit@comma{} Options@comma{} …) to that of a context menu.

For Anju:

@itemize
@item
The highest concern of a main menu section is discoverability.
@item
The highest concern of a context menu is concision.
@end itemize

A common implementation practice in Emacs is to reuse menu keymaps for both the main menu and context menus. This violates the above concerns@comma{} which Anju seeks to address.

The next sub-sections further detail the design concerns with respect to an area where mouse interaction occurs.

@subsubheading Context Menu

A context menu (as its name implies) should constrain itself to commands relevant to @emph{context}. The parameters of this context are usually (although not exclusively) defined by a subset of:

@itemize
@item
Point (cursor) position
@item
Text selection
@item
Mouse cursor position
@item
Major mode
@item
Read-only state (on or off)
@end itemize

Anju takes the opinion that context menus should @emph{not} support general command discovery. The context menu offering should be @emph{concise}. Users seeking command discovery should instead look at the main menu.

@subsubheading Direct Manipulation

Support for direct action based on mouse cursor position is a common user interaction technique. Anju applies this to Emacs window management@comma{} where window creation@comma{} deletion@comma{} and swapping are supported from both the context menu and the mode line.

@subsubheading No Middle Button Bindings

Anju eschews Emacs' default middle mouse button bindings as they presume usage of a @uref{https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Sun_optical_mouse.jpg/960px-Sun_optical_mouse.jpg, 90's style 3-button mouse}. This style of mouse design has long been superseded with a middle @uref{https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg, scroll-wheel+button control}. This widespread hardware change has resulted in the majority of mouse-supporting applications to emphasize scrolling actions with the middle control and clicking actions to the left and right buttons. Anju follows suit@comma{} primarily binding the right mouse button click (down) event to raising a context menu. In addition@comma{} Anju reconfigures commands that were previously bound to the middle button to ones accessible via a context menu.

The only exception Anju makes in this matter is to keep the Emacs default binding of @code{mouse-2} to @code{mouse-yank-primary}.

@node Features
@chapter Features

@cindex Features

Anju offers many enhancements to the mouse interactions provided by Emacs. These enhancements are detailed in the following sections below.

@menu
* Mode Line Features::
* Context Menu Features::
* Main Menu Features::
* Window Management Features::
@end menu

@node Mode Line Features
@section Mode Line Features

@cindex Mode Line Features

The following mode line enhancements are provided by Anju:

@subheading Pop-up Buffer List
@cindex Pop-up Buffer List

On the mode line@comma{} left-click (@code{mouse-1}) on the buffer name to raise a pop-up menu containing a list of open buffers. The contents of this list is controlled by the customizable variable @code{anju-buffer-list-filter-functions}. More info on customizing the buffer list menu can be found in @ref{Mode Line Buffer List Menu Customization, , Mode Line Buffer List Menu Customization}.


@image{images/anju-mode-line-buffer-list,,,,png}

@subheading Window Management
@cindex Window Management

A right-click (@code{mouse-3}) on any blank space on the mode line will pop-up a window management menu.

@image{images/anju-mode-line-window-management,,,,png}

From here@comma{} one can:
@itemize
@item
Delete the window (×)
@item
Split the window horizontally (→)
@item
Split the window vertically (↓)
@item
If multiple windows are shown@comma{} swap the current window.
@end itemize

Note: usage of ``window'' refers to the Emacs definition of it. Refer to @ref{Frames,,,emacs,} for more detail on this.

@subheading Toggle Maximize Window
@cindex Toggle Maximize Window

A left-double-click on any blank space on the mode line will checkpoint the current window configuration@comma{} then maximize the current window (@code{delete-other-windows}). Re-doing the left-double-click will restore the prior window configuration.

@node Context Menu Features
@section Context Menu Features

@cindex Context Menu Features

Anju enhances @code{context-menu-mode} by providing context menu functions to support the following contexts:

@itemize
@item
Selected text
@item
Mode-specific commands
@itemize
@item
Org mode
@item
Dired
@item
Emacs Lisp
@item
Compilation/Grep
@item
Info
@item
Makefile
@end itemize
@item
Rectangles
@item
Version-controlled source
@item
Window management
@item
Full support for @code{context-menu-mode} customization (See @ref{Context Menu Customization, , Context Menu Customization}).
@end itemize

Anju deliberately omits the display of the default mode-specific menu keymaps in the context menu as they are considered redundant to their display in the main menu. Rationale for this is described in @ref{Design Principles and Concerns, , Design Principles and Concerns}. Users can still access the default mode-specific menu keymap by using the binding @kbd{C-<mouse-3>}.

Learn more about the different areas Anju enhances context menus in the links below.

@menu
* Selected Text Commands::
* Org Mode Context Menu::
* Dired Mode Context Menu::
* Info Context Menu::
* Emacs Lisp Context Menu::
* Compilation/Grep Context Menu::
* Makefile Context Menu::
* Rectangle Context Menu::
* Version-Controlled Source::
@end menu

@node Selected Text Commands
@subsection Selected Text Commands

@cindex Selected Text Commands

@image{images/anju-context-menu-region,,,,png}

If a context menu is raised on selected text@comma{} the following menu items are displayed:

@table @asis
@item Occur
Run @code{occur} command to show occurrences of selected text.

@item Style
Applies mode-specific markup to emphasize the selected text (e.g. bold@comma{} italic@comma{} code@comma{} etc.).
@itemize
@item
Available only for @code{org-mode} and @code{markdown-mode}.
@end itemize

@item Transform Text
Applies transforms (upper/lower case@comma{} capitalize) to the selected text.

@item Query Replace
Run @code{query-replace} on selected text.

@item Query Replace Regexp…
Run @code{query-replace-regexp} on selected text.

@item Toggle comment 
Toggles selected text to be commented based on mode.
@itemize
@item
Available only on modes derived from @code{prog-mode} and @code{org-mode}
@end itemize

@item Write Region…
Writes selected text to a user-specified file.

@item Look Up
If a word is selected@comma{} uses @code{dictionary} to look up its definition.

@item Copy as…
If the current buffer is using Org mode@comma{} then this sub-menu is displayed. Learn more about this in @ref{Org “Copy as…” Context Menu, , Org “Copy as…” Context Menu}.
@end table

@node Org Mode Context Menu
@subsection Org Mode Context Menu

@cindex Org Mode Context Menu

Anju provides context-sensitive support for Org mode by providing commands relevant to the type of Org element the point is in. Org elements supported by Anju are:

@itemize
@item
Headline
@item
Item
@item
Table
@end itemize

In addition if text is selected@comma{} then support for styling@comma{} linking@comma{} and copying as a different format are supported.

Note that the Org mode context menu is deliberately restrained in its command offering in accord with Anju's @ref{Design Principles and Concerns, , Design Principles and Concerns}.

It is recommended that the @code{org-mouse} package be loaded when using Anju.

@menu
* Org Headline Context Menu::
* Org Item Context Menu::
* Org Table Context Menu::
* Org Insert Link::
* Org Toggle Images & Show Markup::
* Org “Copy as…” Context Menu::
* Org Paste Context Menu::
@end menu

@node Org Headline Context Menu
@subsubsection Org Headline Context Menu

@cindex Org Headline Context Menu

If the context menu is raised on a headline@comma{} then commands related to TODO state@comma{} change to body@comma{} clocking@comma{} sorting@comma{} and promotion are offered.

@image{images/anju-context-menu-org-headline,,,,png}

@node Org Item Context Menu
@subsubsection Org Item Context Menu

@cindex Org Item Context Menu

If the context menu is raised on a list item@comma{} then commands related to sorting@comma{} cycling bullet-style@comma{} promotion and checkbox operations are provided.

The menu item ``Change to Checkbox'' will convert an item to a checkbox@comma{} with the additional behavior that if the point is at the start of the whole list@comma{} the whole list will be converted.

@image{images/anju-context-menu-org-item,,,,png}

A checkbox can be converted back to a list item using “Change to Item” as shown below. If @code{org-mouse} is loaded then the checkbox state can be toggled between on ('[X]') or off ('[ ]'). Anju provides the “In-Progress [-]” menu item to put the checkbox in an intermediate state.

@image{images/anju-context-menu-org-item-inprogress,,,,png}

Note that checkboxes in screenshots are prettified using @code{prettify-symbols-mode}.

@node Org Table Context Menu
@subsubsection Org Table Context Menu

@cindex Org Table Context Menu

If the context menu is raised in a table@comma{} then table-specific commands are shown.

@image{images/anju-context-menu-org-table,,,,png}

The context menu shows the current Org table cell reference where the point is in (e.g. @code{@@3$2}). Clicking on this reference will copy it to the @code{kill-ring} for subsequent use in a table formula.

If a selected region or rectangle is made whose extents are within the table@comma{} then the table region reference  is displayed.

The “Org Table Region” sub-menu provides commands to cut@comma{} copy@comma{} and paste rectangular regions made in the table. Note that the binding @kbd{C-M-<mouse-1>} lets you make rectangle selections.

@node Org Insert Link
@subsubsection Org Insert Link

@cindex Org Insert Link

@image{images/anju-context-menu-org-link,,,,png}

If the point is on selected text or an existing Org link@comma{} the context menu will have the menu item “Link…” to run the command @code{org-insert-link}. From there you can add or edit a link.

If an Org link has already been stored@comma{} then the menu item “Paste Last Org Link” will be displayed. See more at @ref{Org Paste Context Menu, , Org Paste Context Menu}.

@node Org Toggle Images & Show Markup
@subsubsection Org Toggle Images & Show Markup

@cindex Org Toggle Images & Show Markup

@image{images/anju-context-menu-toggle-images-markup,,,,png}

The Org context menu supports the following menu items except for when the point is in a table:

@table @asis
@item Toggle Images
Toggle display of images when running in GUI@.

@item Show Markup
Reveal or hide display of Org markup.
@end table

@node Org “Copy as…” Context Menu
@subsubsection Org “Copy as…” Context Menu

@cindex Org Copy as Context Menu

@image{images/anju-context-menu-org-copy-as,,,,png}

If text is selected@comma{} the “Copy as…” sub-menu will be presented. This sub-menu will provide different format options to export the selected text to the system clipboard for subsequent pasting. The following formats are supported.

@itemize
@item
GFM  (GitHub Flavored Markdown@comma{} only available if the @code{ox-gfm} (@uref{https://melpa.org/#/ox-gfm, MELPA}) package is installed)
@item
Markdown
@item
@LaTeX{}
@item
HTML
@item
ASCII
@item
Slack (only available if the @code{ox-slack} (@uref{https://melpa.org/#/ox-slack, MELPA}) package is installed)
@item
RTF (only available on macOS)
@end itemize

Users who frequently work with other text-based formats may find this menu useful.

Markdown users may find the companion feature of “Paste Markdown as Org” also useful (@ref{Org Paste Context Menu, , Org Paste Context Menu}).

@node Org Paste Context Menu
@subsubsection Org Paste Context Menu

@cindex Org Paste Context Menu

@image{images/anju-context-menu-enhanced-paste,,,,png}

Anju adds more “Paste” commands that will display given the right context.

@table @asis
@item Paste Last Org Link
If it exists@comma{} this command will insert the last stored Org link.

@item Paste Markdown as Org
If the clipboard (latest yank) is known by the user to be Markdown text@comma{} this command will convert the clipboard text to Org via @code{pandoc}@comma{} then paste (yank) it into the buffer.

@item Paste Media
If an image as been copied into the clipboard@comma{} this menu item will ``paste'' it via the @code{yank-media} command.
@end table

@node Dired Mode Context Menu
@subsection Dired Mode Context Menu

@cindex Dired Mode Context Menu

Anju enhances the context menu support for Dired mode. The screenshot below shows the context menu when the mouse point is over a file.

@image{images/anju-context-menu-dired-copy-to,,,,png}

If the mouse point is over a directory@comma{} the option to insert a view (aka subdir) for it in the buffer is provided.

@image{images/anju-context-menu-dired-insert-subdir,,,,png}

Note that the Dired context menu is intentionally restrained in its command offering in accord with Anju's @ref{Design Principles and Concerns, , Design Principles and Concerns}.

@node Info Context Menu
@subsection Info Context Menu

@cindex Info Context Menu

Anju enhances the context menu support for Info mode. Notable additions include copying the node name to the @code{kill-ring} and opening the node in a web browser.

@image{images/anju-context-menu-info,,,,png}

@node Emacs Lisp Context Menu
@subsection Emacs Lisp Context Menu

@cindex Emacs Lisp Context Menu

Anju enhances the context menu for Emacs Lisp (Elisp) development with support for Edebug and ERT@.

@menu
* Basic Elisp Context Menu::
* Edebug Mode Context Menu::
* ERT Support::
* Extract Lambda (𝜆) Expression::
@end menu

@node Basic Elisp Context Menu
@subsubsection Basic Elisp Context Menu

@cindex Basic Elisp Context Menu

Anju enhances the default Elisp context menu by providing commands for evaluating@comma{} debugging@comma{} and refactoring Elisp. Many of these commands are context-sensitive to point location. If a command does not apply at point@comma{} it will not be shown in the context menu.

If hideshow (@ref{Hideshow,,,emacs,}) support is enabled@comma{} then a sub-menu “Hide/Show” is provided.

The screenshot below shows the context menu raised when the point is on the function @code{foo}. Selecting the menu item “Edebug “foo”” will instrument @code{foo} for debugging. On the next invocation of @code{foo}@comma{} the Edebug debugger will be run. Anju enhances the @ref{Edebug Mode Context Menu, , context menu for Edebug} as well.

@image{images/anju-context-menu-elisp,,,,png}

Note that the Emacs default context menu for Elisp supports Xref (@ref{Xref,,,emacs,}) navigation as well as help (@code{describe-function}) and Info lookup as shown below.

@image{images/anju-context-menu-elisp-built-in,,,,png}

@node Edebug Mode Context Menu
@subsubsection Edebug Mode Context Menu

@cindex Edebug Mode Context Menu

When debugging Elisp using Edebug@comma{} the following context menu offering its many commands is shown.

@image{images/anju-context-menu-edebug,,,,png}

For users new to Edebug@comma{} it is helpful to understand that code execution is sexp-based as opposed to line/function-based in other IDEs.

To better understand Edebug's command set@comma{} a close reading of its manual is recommended (@ref{Edebug,,,elisp,}).

@node ERT Support
@subsubsection ERT Support

@cindex ERT Support


ERT is a built-in package for Emacs that supports automated testing of Elisp (@ref{Top,,,ert,}). Anju provides a convenience command to run an @code{ert-deftest} if the point is within its declaration. The screenshot below shows and example of running the ERT test @code{test-foo}.

@image{images/anju-context-menu-ert,,,,png}

The result of running @code{test-foo} is shown below.

@image{images/anju-context-menu-ert-result,,,,png}

@node Extract Lambda (𝜆) Expression
@subsubsection Extract Lambda (𝜆) Expression

@cindex Extract Lambda (𝜆) Expression

Anju provides support for extracting a lambda (𝜆) expression into a function declaration with the menu item “Extract 𝜆…”. This feature requires that the point be on the @code{lambda} symbol. The screenshots below shows this command in operation.

@image{images/anju-context-menu-extract-lambda-1,,,,png}

The user will be prompted in the mini-buffer for a name of the new function. The example below shows @code{add-two}.

@image{images/anju-context-menu-extract-lambda-2,,,,png}

The result is that a temporary buffer named @code{*add-two*} (the input name is used) holding the new function is created and a reference to the new function (@code{#'add-two}) is substituted in-place at the original location of the lambda expression.

@image{images/anju-context-menu-extract-lambda-3,,,,png}

The @code{*add-two*} buffer can be edited as needed and its contents placed into a desired Elisp file.

@node Compilation/Grep Context Menu
@subsection Compilation/Grep Context Menu

@cindex Compilation/Grep Context Menu


@image{images/anju-context-menu-compilation,,,,png}


If the buffer is the output of a compilation@comma{} then its context menu is populated with commands to either recompile or invoke a new compile command.

If the buffer is the output of a Grep search@comma{} then its context menu is populated with the command to refresh the search.

@node Makefile Context Menu
@subsection Makefile Context Menu

@cindex Makefile Context Menu

@image{images/anju-context-menu-makefile,,,,png}


This context menu offers commands provided by Makefile mode.

@node Rectangle Context Menu
@subsection Rectangle Context Menu

@cindex Rectangle Context Menu

@image{images/anju-context-menu-rectangle,,,,png}

If a rectangle selection is made (@kbd{C-M-<mouse-1>}) or has been killed@comma{} then the “Rectangle” sub-menu is presented in the context menu. Anju treats a rectangle selection with the highest priority; most Anju context menus will @emph{not} display if a rectangle selection is made.

To learn more about rectangle commands@comma{} see @ref{Rectangles,info ``(emacs) Rectangles'',,emacs,}.

@node Version-Controlled Source
@subsection Version-Controlled Source

@cindex Version-Controlled Source
@cindex Magit

@image{images/anju-context-menu-vc,,,,png}

If a context menu is raised on a buffer containing a modified version controlled file@comma{} then support for viewing the difference between the modifications with its previous commit is provided by the menu item “Ediff revision…”.

If Magit 4.4+ is installed@comma{} then different Magit commands depending on context are displayed. If the context menu is raised in a file buffer@comma{} then the menu item ``Magit Dispatch…'' (@code{magit-file-dispatch}) is shown@comma{} otherwise ``Magit Status'' (@code{magit-status}).

@node Main Menu Features
@section Main Menu Features

@cindex Main Menu Features

Anju enhances the menu bar of Emacs by making opinionated changes to its existing menus as well as adding several new ones. These changes are configurable per menu in the main menu (e.g. ``File''@comma{} ``Edit''@comma{} ``Options''@comma{} etc.). For more detail@comma{} see @ref{Main Menu Customization, , Main Menu Customization}.

@menu
* File Menu Features::
* Edit Menu Features::
* Options Menu Features::
* Bookmarks Menu Features::
* Text Menu Features::
* Index Menu (imenu) Features::
* Tools Menu Features::
* Help Menu Features::
@end menu

@node File Menu Features
@subsection File Menu Features

@cindex File Menu Features

Anju makes the following modifications to the menu bar @strong{File} menu:

@itemize
@item
Adds a “Swap Window ›” sub-menu.
@item
Updates the “New Frame on Display Server@dots{}” menu item to only display on an X11 system.
@item
Updates the “New Frame on Monitor…” menu item to only display if more than one monitor is detected.
@end itemize

For the macOS NS variant of Emacs@comma{} the above update to “New Frame on Monitor…” will only work on Emacs version 31+.

These modifications are optional. For more detail@comma{} see @ref{File Menu Customization, , File Menu Customization}.

@node Edit Menu Features
@subsection Edit Menu Features

@cindex Edit Menu Features

@image{images/anju-main-menu-edit-search-in-files,,,,png}

Anju makes the following modifications to the menu bar @strong{Edit} menu:

@itemize
@item
Adds “Search in Files…” to the @strong{Search} sub-menu.

@item
Adds the “Rectangle” sub-menu of commands (@ref{Rectangles,,,emacs,}).

@item
Adds the “Transpose  ⇄” sub-menu of commands to transpose different text quantities.

@item
Adds the “Move Text” sub-menu to move different text quantities.

@item
Adds the “Delete” sub-menu to delete different text quantities.

@item
Adds the menu item “Flush Lines…”.

@item
Adds the menu item “Keep Lines…”.

@item
Adds the menu item “Align Regexp…”.

@item
Adds the menu item “Duplicate”.
@end itemize

On the macOS NS variant of Emacs@comma{} the following menu items are added.

@itemize
@item
“Colors” - display the macOS system color picker dialog.

@item
“Emoji & Symbols” - display the macOS system Emoji & Symbols dialog.
@end itemize

The commands provided by the above additions to the @strong{Edit} menu are shown below.

@itemize
@item
Search
@itemize
@item
Search in Files… (@code{rgrep})
@end itemize

@item
Rectangle
@itemize
@item
Cut (@code{kill-rectangle})
@item
Copy (@code{copy-rectangle-as-kill})
@item
Paste (@code{yank-rectangle})
@item
Delete (@code{delete-rectangle})
@item
Replace… (@code{string-rectangle})
@item
Insert… (@code{string-insert-rectangle})
@item
Number (@code{number-rectangle-lines})
@item
Clear (@code{clear-rectangle})
@item
Blank (@code{open-rectangle})
@item
Delete leading spaces (@code{delete-whitespace-rectangle})
@end itemize

@item
Transpose ⇄
@itemize
@item
Characters (@code{transpose-chars})
@item
Words (@code{transpose-words})
@item
Lines (@code{transpose-lines})
@item
Sentences (@code{transpose-sentences})
@item
Paragraphs (@code{transpose-paragraphs})
@item
Regions (@code{transpose-regions})
@item
Balanced Expressions (sexps) (@code{transpose-sexps})
@end itemize

@item
Move Text
@itemize
@item
Word → (@code{casual-editkit-move-word-forward})
@item
Word ← (@code{casual-editkit-move-word-backward})
@item
Sentence → (@code{casual-editkit-move-sentence-forward})
@item
Sentence ← (@code{casual-editkit-move-sentence-backward})
@item
Balanced Expression (sexp) → (@code{casual-editkit-move-sexp-forward})
@item
Balanced Expression (sexp) ← (@code{casual-editkit-move-sexp-backward})
@end itemize

@item
Delete
@itemize
@item
Join Line (@code{join-line})
@item
Just One Space (@code{just-one-space})
@item
Horizontal Space (@code{delete-horizontal-space})
@item
Pair (@code{delete-pair})
@item
Duplicate Lines (@code{delete-duplicate-lines})
@item
Blank Lines (@code{delete-blank-lines})
@item
Whitespace Cleanup (@code{whitespace-cleanup})
@item
Trailing Whitespace (@code{delete-trailing-whitespace})
@item
Zap up to… (@code{zap-up-to-char})
@item
Zap to… (@code{zap-to-char})
@end itemize

@item
Flush Lines… (@code{flush-lines})

@item
Keep Lines… (@code{keep-lines})

@item
Align Regexp… (@code{align-regexp})

@item
Duplicate (@code{duplicate-dwim})

@item
Colors (@code{ns-popup-color-panel}) (only on  macOS NS)

@item
Emoji & Symbols (@code{ns-do-show-character-palette}) (only on macOS NS)
@end itemize


Note that a menu command can be run again immediately after it has been issued using the @code{repeat} command (binding @kbd{C-x z}). This is useful when using the move text commands.

These modifications are optional. For more detail@comma{} see @ref{Edit Menu Customization, , Edit Menu Customization}.

@node Options Menu Features
@subsection Options Menu Features

@cindex Options Menu Features

Anju makes the presumption that most Emacs users do not use the CUA mode configuration in the menu bar @strong{Options} menu. As such@comma{} the “Cut/Paste with C-x/C-c/C-v (CUA Mode)” menu item is removed.

This modification is optional. For more detail@comma{} see @ref{Options Menu Customization, , Options Menu Customization}.

@node Bookmarks Menu Features
@subsection Bookmarks Menu Features

@cindex Bookmarks Menu Features

Anju adds a @strong{Bookmarks} menu to the main menu to work with Emacs-specific bookmarks.

@image{images/anju-main-menu-bookmarks,,,,png}

This modification is optional. For more detail@comma{} see @ref{Bookmarks Menu Customization, , Bookmarks Menu Customization}.

The menu hierarchy of the @strong{Bookmarks} menu is described below with the actual command shown in parenthesis next to its label.

@itemize
@item
Edit Bookmarks (@code{list-bookmarks})
@item
Add Bookmark… (@code{bookmark-set-no-overwrite})
@item
Jump to Bookmark… (@code{bookmark-jump})
@end itemize

@node Text Menu Features
@subsection Text Menu Features

@cindex Text Menu Features

@image{images/anju-main-menu-text,,,,png}

If the major mode of the current buffer is derived from @code{text-mode}@comma{} then a @strong{Text} menu is displayed in the menu bar.

The menu hierarchy of the @strong{Text} menu is described below with the actual command shown in parenthesis next to its label.

@itemize
@item
Transform Text (@code{anju-transform-text-menu})
@itemize
@item
Make Upper Case (@code{upcase-region})
@item
Make Lower Case (@code{downcase-region})
@item
Capitalize (@code{capitalize-region})
@end itemize

@item
Style (@code{anju-style-menu})
@itemize
@item
Bold (@code{anju-style-bold})
@item
Italic (@code{anju-style-italic})
@item
Code (@code{anju-style-code})
@item
Underline (@code{anju-style-underline})
@item
Verbatim (@code{anju-style-verbatim})
@item
Strike Through (@code{anju-style-strike-through})
@item
Remove (@code{anju-style-remove})
@end itemize

@item
Center (@code{anju-center-text-menu})
@itemize
@item
Line (@code{center-line})
@item
Region (@code{center-region})
@item
Paragraph (@code{center-paragraph})
@end itemize

@item
Fill (@code{anju-fill-text-menu})
@itemize
@item
Paragraph (@code{fill-paragraph})
@item
Region (@code{fill-region})
@item
Region as paragraph (@code{fill-region-as-paragraph})
@item
Individual paragraphs (@code{fill-individual-paragraphs})
@item
Non-uniform paragraphs (@code{fill-nonuniform-paragraphs})
@end itemize

@item
Auto Fill (@code{toggle-text-mode-auto-fill})
@end itemize

Note the @strong{Style} menu is visible only for Org and Markdown modes.

This modification is optional. For more detail@comma{} see @ref{Text Menu Customization, , Text Menu Customization}.

@node Index Menu (imenu) Features
@subsection Index Menu (imenu) Features

@cindex Index Menu Features

@image{images/anju-main-menu-imenu,,,,png}


For certain modes that support Imenu (@ref{Imenu,,,emacs,})@comma{} Anju will add an @strong{Index} menu to the menu bar via the function  @code{imenu-add-menubar-index}.

Modes supported this way by Anju are:

@itemize
@item
@code{prog-mode} derived modes
@item
@code{org-mode}
@item
@code{markdown-mode}
@item
@code{makefile-mode}
@end itemize

This modification is optional. For more detail@comma{} see @ref{Imenu Menu Customization, , Imenu Menu Customization}.

@node Tools Menu Features
@subsection Tools Menu Features

@cindex Tools Menu Features

@image{images/anju-main-menu-tools,,,,png}


Anju makes the following modifications to the menu bar @strong{Tools} menu:

@table @asis
@item Adds the “Macro Recorder” sub-menu
Commands to create@comma{} run@comma{} edit@comma{} and debug  @ref{Macro Recorder Menu, , keyboard macros}.

@item Adds global Org commands
Provide general access to these commands
@itemize
@item
“Org Store Link” (@code{org-store-link})
@item
“Org Capture…” (@code{org-capture})
@item
“Org Agenda…” (@code{org-agenda})
@end itemize
@end table

@menu
* Macro Recorder Menu::
@end menu

@node Macro Recorder Menu
@subsubsection Macro Recorder Menu

@cindex Macro Recoder Menu

Keyboard macros offer workflow automation in Emacs in a ``no-code'' fashion.  Anju showcases this capability by providing a menu of keyboard macro commands in the menu bar Tools menu.


@image{images/anju-main-menu-tools-kmacro,,,,png}


Note that both keystroke and mouse menu actions can be recorded by a keyboard macro.

When recording a keyboard macro@comma{} the menu is modified to provide access to counter and query user (prompt) commands.

@image{images/anju-kmacro-menu-recording,,,,png}


For more reading on keyboard macros@comma{} see @ref{Keyboard Macros,,,emacs,}.

@node Help Menu Features
@subsection Help Menu Features

@cindex Help Menu Features

Anju re-organizes the @strong{Help} menu as shown below. The re-organization emphasizes showing documentation in a new frame@comma{} takes out non-help related menu items@comma{} and offers more concision.

@image{images/anju-main-menu-help,,,,png}

This modification is optional. For more detail@comma{} see @ref{Help Menu Customization, , Help Menu Customization}.

For experienced users@comma{} the ``Emacs Tutorial'' menu items can be removed via the customizable variable @code{anju-help-menu-remove-emacs-tutorial}.

@node Window Management Features
@section Window Management Features

@cindex Window Management Features

Window management via mouse interaction is provided for through the @ref{Mode Line Features, , mode line} and @ref{Context Menu Features, , context menu}. More detail is provided in those sections.

@node Requirements
@chapter Requirements

@cindex Requirements

Anju requires Emacs 29.1+@comma{} Casual 2.13+@comma{} Markdown Mode 2.7+.

Certain menus require more installed software:

@itemize
@item
Anju Dired Support: GNU Coreutils (@code{ls})
@item
Markdown import to Org: pandoc
@end itemize

Anju provides optional support for Magit 4.4+.

@node Install
@chapter Install

@cindex Install
@vindex context-menu-mode
@vindex anju-init

To install Anju@comma{} add the command @code{anju-init} to your Emacs initialization file.

@lisp
(anju-init)
@end lisp

This command will initialize @code{context-menu-mode} and reconfigure the following mouse menus and bindings:

@itemize
@item
Legacy mouse bindings
@item
Mode line bindings
@item
Main menu
@item
Context menus for different modes
@end itemize

The @code{anju-init} command can also be invoked via @code{M-x}.

Anju supports a high degree of customization. Users who wish this should make a deep read of the @ref{Customization, , Customization} section.

While not required@comma{} the following additions to your Emacs initialization file can further enhance your mouse experience:

@itemize
@item
Enable @code{org-mouse}
@lisp
(require 'org-mouse)
@end lisp

@item
Add Markdown export support to Org mode
@itemize
@item
@code{M-x} @code{customize-variable} @code{org-export-backends}@comma{} check @code{md} option.
@end itemize

@item
Globally bind @code{C-x 1} to @code{anju-toggle-one-window}.

@lisp
(keymap-global-set "C-x 1" #'anju-toggle-one-window)
@end lisp

@item
Set @code{use-file-dialog} to @code{t} to support mouse-driven-only dialog interactions@comma{} or @code{nil} to always get a mini-buffer prompt.
@end itemize

@node Customization
@chapter Customization

@cindex Customization

Anju provides a number of ways to customize mouse interactions in Emacs. In many cases@comma{} Anju leverages off existing Emacs customization options@comma{} particularly around defining and modifying menus. Users who wish to modify menus in Emacs should familiarize themselves with menu keymaps (@ref{Menu Keymaps,,,elisp,}) and the Easy Menu (@ref{Easy Menu,,,elisp,}) library.

Customization options for the different areas Anju covers are detailed below.

@menu
* Anju Initialization (@code{anju-init})::
* Context Menu Customization::
* Mode Line Buffer List Menu Customization::
* Main Menu Customization::
@end menu

@node Anju Initialization (@code{anju-init})
@section Anju Initialization (@code{anju-init})

@cindex Anju Initialization
@vindex anju-init
@vindex anju-reconfigure-context-menu-functions-enable
@vindex anju-mode-line-bindings-enable
@vindex anju-unset-legacy-mouse-bindings-enable
@vindex anju-reconfigure-main-menu-enable
@vindex anju-help-menu-remove-emacs-tutorial
@vindex anju-reconfigure-main-menu-hook

Anju has a number of customizable variables that determine the behavior of @code{anju-init}. They are:

@table @asis
@item @code{anju-reconfigure-context-menu-functions-enable}
Enable reconfiguration of the variable @code{context-menu-functions} with Anju-defined menu functions.

If @code{context-menu-functions} is previously set via @code{customize-variable} then @code{anju-init} will make no changes to @code{context-menu-functions} regardless of how  @code{anju-reconfigure-context-menu-functions-enable} is set.

@item @code{anju-mode-line-bindings-enable}
Enable Anju-defined bindings for the mode line.

@item @code{anju-unset-legacy-mouse-bindings-enable}
Remove bindings using @code{mouse-2}.

@item @code{anju-reconfigure-main-menu-enable}
Top-level variable to reconfigure the main menu.

If @code{anju-reconfigure-main-menu-enable} is @code{t}@comma{} the following variables determine how the main menu is reconfigured:

@table @asis
@item @code{anju-reconfigure-main-menu-hook}
a list of functions@comma{} each modifying a menu of the main menu.

@item @code{anju-help-menu-remove-emacs-tutorial}
control if the Emacs tutorial menu items are shown.
@end table
@end table

By default@comma{} all the above @code{*-enable} variables are set to @code{t}.  Users preferring to make granular changes to @code{anju-init} can invoke @code{M-x} @code{customize-group} @code{anju}.

@node Context Menu Customization
@section Context Menu Customization

@cindex Context Menu Customization
@vindex context-menu-mode
@vindex context-menu-functions


Anju uses @code{context-menu-mode} (introduced in Emacs 28) to define its context menu behavior. This is accomplished through the customizable hook variable @code{context-menu-functions}.

@code{context-menu-functions} is a list of functions where each function has two arguments:

@itemize
@item
@code{menu} : reference to the context menu
@item
@code{click} : a mouse event
@end itemize

When the context menu is raised@comma{} typically via right-click (@code{mouse-3})@comma{} each function in @code{context-menu-functions} is run@comma{} populating the context menu.

The following example Elisp illustrates an implementation of a context menu function.

@lisp
(defun anju-context-menu-wordcount (menu click)
  "Context menu hook function for wordcount commands.

- MENU: menu
- CLICK: event

This function is intended to be hooked into `context-menu-functions'."
  (when (and (derived-mode-p 'text-mode) (not (anju-at-org-table-p)))
    (save-excursion
      (mouse-set-point click)
      (anju-context-menu-item-separator menu count-words-separator)
      (easy-menu-add-item menu nil [count-words count-words
                                    :label "Count Words"
                                    :help "Count words"])))
  menu)
@end lisp


Defining how a menu item is context-sensitive can be determined in multiple places:

@enumerate
@item
At the time of menu item definition
@item
At a higher level.
@end enumerate

The @emph{context} is determined by a predicate which can take into account different things@comma{} among them:

@itemize
@item
Selected Text (@code{use-region-p})
@item
Major mode
@item
Cursor (Point) position
@item
Mouse position
@end itemize

In the example above@comma{} the context predicate tests if the major mode is derived from @code{text-mode} @emph{and} if point is not inside an Org table (@code{anju-at-org-table-p}).  Note that it is defined at a higher level to avoid instantiating menu items if the context does not apply.

The context predicate can be embedded in the menu item definition itself. See more about this with the @code{:visible} and @code{:active} keywords for the macro @code{easy-menu-define} (@ref{Easy Menu,,,elisp,}).

It is up to the implementer to determine where to best define and apply the context predicate.

@menu
* Customizing context-menu-functions::
* Anju Context Menu Functions::
@end menu

@node Customizing context-menu-functions
@subsection Customizing context-menu-functions

@cindex Customizing context-menu-functions
@vindex context-menu-functions

@image{images/anju-context-menu-customize,,,,png}

It is recommended to use the @code{customize-variable} command to configure @code{context-menu-functions} instead of using @code{add-hook} for the following reasons:

@itemize
@item
A visual UI is provided showing what choices for built-in context menu functions are available.

@itemize
@item
Anju modifies the choice selection to include Anju-defined context menu functions.
@end itemize

@item
Users can insert their own custom function.

@item
Top-down ordering of functions will similarly determine the order of menu items in the context menu.
@end itemize


Learn more about the context menu functions provided by Anju in the section @ref{Anju Context Menu Functions, , Anju Context Menu Functions}.

@node Anju Context Menu Functions
@subsection Anju Context Menu Functions

@cindex Anju Context Menu Functions
@vindex anju-context-menu-dired
@vindex anju-context-menu-org-mode
@vindex anju-context-menu-make-mode
@vindex anju-context-menu-compile
@vindex anju-context-menu-scratch
@vindex anju-context-menu-buffers
@vindex anju-context-menu-region
@vindex anju-context-menu-region-extension
@vindex anju-context-menu-narrow
@vindex anju-context-menu-open-in
@vindex anju-context-menu-vc
@vindex anju-context-menu-markup
@vindex anju-context-menu-wordcount
@vindex anju-context-menu-window
@vindex anju-context-menu-dictionary
@vindex anju-context-menu-elisp
@vindex anju-context-menu-edebug-eval
@vindex anju-context-menu-rectangle

Anju provides the following context menu functions for convenience. They can be used as-is or serve as a base for user-customized behavior.

@table @asis
@item @code{anju-context-menu-dired}
Dired commands.

@item @code{anju-context-menu-org-mode} 
Org mode commands.

@item @code{anju-context-menu-make-mode} 
Makefile mode commands.

@item @code{anju-context-menu-compile} 
Compilation (or Grep) mode commands.

@item @code{anju-context-menu-scratch} 
Open scratch buffer.

@item @code{anju-context-menu-buffers}
Buffer navigation commands.

@item @code{anju-context-menu-region}
Commands for selected text.

@item @code{anju-context-menu-region-extension}
Commands for extending the menu items provided by the built-in @code{context-menu-region} hook. Anju puts the Org-dependent “Paste” commands here.

@item @code{anju-context-menu-dictionary}
Look up definition of selected word with @code{dictionary}.

@item @code{anju-context-menu-narrow}
Narrow-related commands.

@item @code{anju-context-menu-open-in}
Open in Dired.

@item @code{anju-context-menu-vc}
Version control related commands.
If Magit 4.4+ is installed@comma{} then calls to it are made from here.

@item @code{anju-context-menu-markup}
Commands to show/hide text markup (e.g. Org@comma{} Markdown).

@item @code{anju-context-menu-wordcount}
Word count command.

@item @code{anju-context-menu-window}
Window management commands.

@item @code{anju-context-menu-elisp}
Emacs Lisp commands.

@item @code{anju-context-menu-edebug-eval}
Edebug commands.

@item @code{anju-context-menu-rectangle}
Rectangle commands.
@end table

@node Mode Line Buffer List Menu Customization
@section Mode Line Buffer List Menu Customization

@cindex Mode Line Buffer List Menu Customization
@vindex anju-buffer-list-filter-functions
@vindex anju-mode-line-buffer-list-function
@vindex anju-buffer-list-plain-filter
@vindex anju-buffer-list-project-filter
@vindex anju-buffer-list-compilation-filter
@vindex anju-buffer-list-grep-filter
@vindex anju-buffer-list-xref-filter
@vindex anju-buffer-list-eshell-filter
@vindex anju-buffer-list-shell-filter
@vindex anju-buffer-list-info-filter
@vindex anju-buffer-list-help-filter
@vindex anju-buffer-list-menu-items
@vindex anju-popup-buffer-menu

The pop-up buffer list menu can be customized two ways:

@enumerate
@item
Customizing the variable @code{anju-buffer-list-filter-functions}@comma{} a list of filter functions that are run each time the pop-up menu is raised when left-clicking the mode line buffer name.

@item
Customizing the variable @code{anju-mode-line-buffer-list-function}@comma{} which gives a user complete control on what is displayed in the pop-up menu.
@end enumerate


@subheading anju-buffer-list-filter-functions

This variable is an alist used by the function @code{anju-buffer-list-menu-items} to populate the list of buffers used in the pop up menu @code{anju-popup-buffer-menu}.

This alist is filled using the following key@comma{} value pair types:

@table @asis
@item key
a buffer list filter function
@item value
integer used as the maximum count of buffers to use from the filter function
@end table

The buffer list filter function is of the form @code{(filter-fn (buffers &optional count))} where buffers is a list of buffers (usually @code{buffer-list}) and count is the maximum count of buffers to use.

The order of the buffer list presumes the most recently used buffers are
at the front of the list.

Anju provides the following buffer filters:

@table @asis
@item @code{anju-buffer-list-project-filter}
buffers within the same project whose name is not marked as special (a name wrapped in ‘*’).
@item @code{anju-buffer-list-plain-filter}
buffers whose name is not marked as special (a name wrapped in ‘*’).
@item @code{anju-buffer-list-compilation-filter}
buffers whose major mode is @code{compilation-mode}.
@item @code{anju-buffer-list-grep-filter}
buffers whose major mode is @code{grep-mode}.
@item @code{anju-buffer-list-xref-filter}
buffers whose major mode is @code{xref--xref-buffer-mode}.
@item @code{anju-buffer-list-eshell-filter}
buffers whose major mode is @code{eshell-mode.}
@item @code{anju-buffer-list-shell-filter}
buffers whose major mode is @code{shell-mode}.
@item @code{anju-buffer-list-info-filter}
buffers whose major mode is @code{Info-mode}.
@item @code{anju-buffer-list-help-filter}
buffers whose major mode is @code{help-mode}.
@end table

Users can customize @code{anju-buffer-list-filter-functions} to re-compose or add their own filters to define the resulting buffer list returned by @code{anju-buffer-list-menu-items}. It is recommended that the @code{customize-variable} command be used to accomplish this.

By default @code{anju-buffer-list-filter-functions} contains the following filters:

@itemize
@item
@code{anju-buffer-list-project-filter}
@item
@code{anju-buffer-list-compilation-filter}
@item
@code{anju-buffer-list-grep-filter}
@item
@code{anju-buffer-list-xref-filter}
@item
@code{anju-buffer-list-eshell-filter}
@item
@code{anju-buffer-list-shell-filter}
@item
@code{anju-buffer-list-info-filter}
@item
@code{anju-buffer-list-help-filter}
@end itemize

@subheading anju-mode-line-buffer-list-function
@vindex anju-mode-line-buffer-list-function

Function that populates the mode line buffer name popup menu.

Assign this variable to a function that returns a value that conforms to the @code{MENU} parameter of the command @code{popup-menu}.

This setting allows for customization of the buffer list (or any other menu content) when the mode line buffer name (identifier) is clicked (typically with @code{mouse-1}).

Users who wish define their own menu should override this value with their own function. It is recommended that such users look at the source to @code{anju-buffer-list-menu-items} as a start to defining their own menu function.

@node Main Menu Customization
@section Main Menu Customization

@cindex Main Menu Customization

Anju uses the customizable hook variable @code{anju-reconfigure-main-menu-hook} to customize the menu bar.

@code{anju-reconfigure-main-menu-hook} is a list of hook functions@comma{}  where each function is designed to modify a different menu of the menu bar (e.g. ``File''@comma{} ``Edit''@comma{} ``Options''@comma{} etc.). This hook is run in the command @code{anju-init}.

Detailed below are the different hook functions provided for by Anju.

Users are free to implement their own hook functions to add to @code{anju-reconfigure-main-menu-hook}. Users who wish to do this should familiarize themselves with menu keymaps (@ref{Menu Keymaps,,,elisp,}) and the Easy Menu (@ref{Easy Menu,,,elisp,}) library.

Note that Anju's implementation of hook functions to each affect a specific menu in the menu bar is by convention.

For more info on hook variables see @ref{Hooks,,,emacs,}.

@menu
* File Menu Customization::
* Edit Menu Customization::
* Options Menu Customization::
* Text Menu Customization::
* Bookmarks Menu Customization::
* Help Menu Customization::
* Imenu Menu Customization::
* Tools Menu Customization::
@end menu

@node File Menu Customization
@subsection File Menu Customization

@cindex File Menu Customization
@vindex anju-main-menu--reconfigure-file

Anju customizes the @strong{File} menu using the hook function @code{anju-main-menu--reconfigure-file}.

Add this hook function to @code{anju-reconfigure-main-menu-hook} to enable customization of the @strong{File} menu.

If @code{customize-variable} is used to configure @code{anju-reconfigure-main-menu-hook}@comma{} then a checkbox interface to enable  @code{anju-main-menu--reconfigure-file} is displayed.

@code{anju-main-menu--reconfigure-file} supports the following customization variable:

@table @asis
@item @code{anju-file-menu-replace-make-frame-on}
If non-nil@comma{} the following menu items are replaced with more context-specific behavior:

@itemize
@item
“New Frame on Display Server@dots{}” - will only display if on an X11 system.
@item
“New Frame on Monitor@dots{}” - will only display if more than one monitor is detected.
@end itemize
@end table

@node Edit Menu Customization
@subsection Edit Menu Customization

@cindex Edit Menu Customization
@vindex anju-main-menu--reconfigure-edit

Anju customizes the @strong{Edit} menu using the hook function @code{anju-main-menu--reconfigure-edit}.

Add this hook function to @code{anju-reconfigure-main-menu-hook} to enable customization of the @strong{Edit} menu.

If @code{customize-variable} is used to configure @code{anju-reconfigure-main-menu-hook}@comma{} then a checkbox interface to enable  @code{anju-main-menu--reconfigure-edit} is displayed.

@node Options Menu Customization
@subsection Options Menu Customization

@cindex Options Menu Customization
@vindex anju-main-menu--reconfigure-options

Anju customizes the @strong{Options} menu using the hook function @code{anju-main-menu--reconfigure-options}.

Add this hook function to @code{anju-reconfigure-main-menu-hook} to enable customization of the @strong{Options} menu.

If @code{customize-variable} is used to configure @code{anju-reconfigure-main-menu-hook}@comma{} then a checkbox interface to enable  @code{anju-main-menu--reconfigure-options} is displayed.

@node Text Menu Customization
@subsection Text Menu Customization

@cindex Text Menu Customization
@vindex anju-main-menu--reconfigure-text-mode

Anju customizes the @strong{Text} menu using the hook function @code{anju-main-menu--reconfigure-text-mode}.

Add this hook function to @code{anju-reconfigure-main-menu-hook} to enable customization of the @strong{Text} menu.

If @code{customize-variable} is used to configure @code{anju-reconfigure-main-menu-hook}@comma{} then a checkbox interface to enable  @code{anju-main-menu--reconfigure-text-mode} is displayed.

Note that the @strong{Text} menu is only displayed when the current major mode is derived from @code{text-mode}.

@node Bookmarks Menu Customization
@subsection Bookmarks Menu Customization

@cindex Bookmarks Menu Customization
@vindex anju-main-menu--reconfigure-bookmarks

Anju adds the @strong{Bookmarks} menu to the menu bar using the hook function @code{anju-main-menu--reconfigure-bookmarks}.

Add this hook function to @code{anju-reconfigure-main-menu-hook} to add the @strong{Bookmarks} menu.

If @code{customize-variable} is used to configure @code{anju-reconfigure-main-menu-hook}@comma{} then a checkbox interface to enable  @code{anju-main-menu--reconfigure-bookmarks} is displayed.

@node Help Menu Customization
@subsection Help Menu Customization

@cindex Help Menu Customization
@vindex anju-main-menu--reconfigure-help
@vindex anju-help-menu-remove-emacs-tutorial

Anju customizes the @strong{Help} menu using the hook function @code{anju-main-menu--reconfigure-help}.

Add this hook function to @code{anju-reconfigure-main-menu-hook} to enable customization of the @strong{Help} menu.

If @code{customize-variable} is used to configure @code{anju-reconfigure-main-menu-hook}@comma{} then a checkbox interface to enable  @code{anju-main-menu--reconfigure-help} is displayed.

@code{anju-main-menu--reconfigure-help} supports the following customization variable:

@table @asis
@item @code{anju-help-menu-remove-emacs-tutorial}
if non-nil@comma{} then remove the Emacs tutorial menu items. (default @code{t})
@end table

@node Imenu Menu Customization
@subsection Imenu Menu Customization

@cindex Imenu Menu Customization
@vindex anju-main-menu--reconfigure-imenu

Anju adds the @strong{Index} menu to the menu bar using the hook function @code{anju-main-menu--reconfigure-imenu}.

Add this hook function to @code{anju-reconfigure-main-menu-hook} to add the @strong{Index} menu.

If @code{customize-variable} is used to configure @code{anju-reconfigure-main-menu-hook}@comma{} then a checkbox interface to enable  @code{anju-main-menu--reconfigure-imenu} is displayed.


Anju's support for Imenu covers the following modes:

@itemize
@item
@code{prog-mode} derived modes
@item
@code{makefile-mode}
@item
@code{org-mode}
@item
@code{markdown-mode}
@end itemize

For more info on Imenu see @ref{Imenu,,,emacs,}.

@node Tools Menu Customization
@subsection Tools Menu Customization

@cindex Tools Menu Customization
@vindex anju-main-menu--reconfigure-tools

Anju customizes the @strong{Tools} menu using the hook function @code{anju-main-menu--reconfigure-tools}.

Add this hook function to @code{anju-reconfigure-main-menu-hook} to enable customization of the @strong{Tools} menu.

If @code{customize-variable} is used to configure @code{anju-reconfigure-main-menu-hook}@comma{} then a checkbox interface to enable  @code{anju-main-menu--reconfigure-tools} is displayed.

@node Future Work
@chapter Future Work

@cindex Future Work

Work on Anju is on-going. Plans for future enhancements include:

@itemize
@item
Support for more built-in modes
@item
Further changes to the main menu
@end itemize

Although much consideration on both the user and developer experience has been made@comma{} they are both subject to change in future releases if a better approach presents itself.

@node Feedback & Discussion
@chapter Feedback & Discussion

@cindex Feedback
Please report any feedback about Anju to the @uref{https://github.com/kickingvegas/anju/issues, issue tracker on GitHub}.

@cindex Discussion
To participate in general discussion about using Anju@comma{} please join the @uref{https://github.com/kickingvegas/anju/discussions, discussion group}.

@node Sponsorship
@chapter Sponsorship

@cindex Sponsorship

It costs money to make@comma{} enhance@comma{} and maintain Anju as ideologically free software. If you enjoy using Anju@comma{} please buy me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas, buymeacoffee.com/kickingvegas}

@node About Anju
@chapter About Anju

@cindex About Anju

@uref{https://github.com/kickingvegas/anju, Anju} was conceived and crafted by Charles Choi in San Francisco@comma{} California.

Thank you for using Anju.

Always choose love.

@node Acknowledgments
@chapter Acknowledgments

@cindex Acknowledgments

Thanks goes out to the contributors to @code{mouse.el}@comma{} whose work this package builds upon.

@node Main Index
@chapter Main Index

Index for this user guide.

@printindex cp

@node Variable Index
@chapter Variable Index

Variables@comma{} functions@comma{} commands@comma{} and menus referenced by this user guide.

@printindex vr

@bye
